<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Coupon_model extends CI_Model
{

    public $table = 'coupon';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('code', $q);
	$this->db->or_like('category_id', $q);
	$this->db->or_like('from_date', $q);
	$this->db->or_like('to_date', $q);
	$this->db->or_like('total', $q);
	$this->db->or_like('discount', $q);
	$this->db->or_like('date_created', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('code', $q);
	$this->db->or_like('category_id', $q);
	$this->db->or_like('from_date', $q);
	$this->db->or_like('to_date', $q);
	$this->db->or_like('total', $q);
	$this->db->or_like('discount', $q);
	$this->db->or_like('date_created', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Coupon_model.php */
/* Location: ./application/models/Coupon_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-08 05:07:34 */
/* http://harviacode.com */